import type { MacroChartPreset, MacroSeriesDefinition } from "./types";
import { stooqSeriesDefinitionFromId } from "./stooq";

export const MACRO_SERIES_CATALOG: readonly MacroSeriesDefinition[] = [
  {
    id: "sp500",
    label: "S&P 500",
    shortLabel: "S&P 500",
    group: "equity",
    unit: "index",
    frequency: "daily",
    sourcePath: "/data/indices/sp500.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "미국 대형주 지수",
    defaultTransform: "rebase100",
    colorToken: "brand",
  },
  {
    id: "nasdaq",
    label: "Nasdaq",
    shortLabel: "Nasdaq",
    group: "equity",
    unit: "index",
    frequency: "daily",
    sourcePath: "/data/indices/nasdaq.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "나스닥 지수",
    defaultTransform: "rebase100",
    colorToken: "brandAlt",
  },
  {
    id: "vix",
    label: "VIX",
    shortLabel: "VIX",
    group: "sentiment",
    unit: "index",
    frequency: "daily",
    sourcePath: "/data/sentiment/vix.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "주식시장 변동성 지수",
    colorToken: "warn",
  },
  {
    id: "move",
    label: "MOVE",
    shortLabel: "MOVE",
    group: "sentiment",
    unit: "index",
    frequency: "daily",
    sourcePath: "/data/sentiment/move.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "채권시장 변동성 지수",
    colorToken: "warn",
  },
  {
    id: "cnn_fear_greed",
    label: "CNN Fear & Greed",
    shortLabel: "Fear/Greed",
    group: "sentiment",
    unit: "score",
    frequency: "daily",
    sourcePath: "/data/sentiment/cnn-fear-greed.json",
    accessor: { kind: "array", valueKey: "score" },
    description: "CNN 공포와 탐욕 점수",
    colorToken: "neutral",
  },
  {
    id: "cnn_put_call",
    label: "Put/Call",
    shortLabel: "Put/Call",
    group: "sentiment",
    unit: "score",
    frequency: "daily",
    sourcePath: "/data/sentiment/cnn-put-call.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "풋/콜 심리 지표",
    colorToken: "neutral",
  },
  {
    id: "aaii_spread",
    label: "AAII Bull-Bear",
    shortLabel: "AAII Spread",
    group: "sentiment",
    unit: "spread",
    frequency: "weekly",
    sourcePath: "/data/sentiment/aaii.json",
    accessor: { kind: "arrayDerived", derive: "aaii_spread" },
    description: "AAII 강세-약세 응답 차이",
    colorToken: "info",
  },
  {
    id: "cftc_sp500_net",
    label: "CFTC S&P Net",
    shortLabel: "CFTC Net",
    group: "sentiment",
    unit: "contracts",
    frequency: "weekly",
    sourcePath: "/data/sentiment/cftc-sp500.json",
    accessor: { kind: "array", valueKey: "net" },
    description: "S&P 500 선물 순포지션",
    colorToken: "info",
  },
  {
    id: "crypto_fear_greed",
    label: "Crypto Fear & Greed",
    shortLabel: "Crypto F/G",
    group: "sentiment",
    unit: "score",
    frequency: "daily",
    sourcePath: "/data/sentiment/crypto-fear-greed.json",
    accessor: { kind: "array", valueKey: "value" },
    description: "크립토 공포와 탐욕 점수",
    colorToken: "neutral",
  },
  {
    id: "tga",
    label: "Treasury General Account",
    shortLabel: "TGA",
    group: "liquidity",
    unit: "usd_million",
    frequency: "daily",
    sourcePath: "/data/macro/tga.json",
    accessor: { kind: "seriesArray", valueKey: "val" },
    description: "미 재무부 일반계정 잔액",
    defaultTransform: "rebase100",
    colorToken: "info",
  },
  {
    id: "stablecoins",
    label: "Stablecoin Supply",
    shortLabel: "Stablecoins",
    group: "liquidity",
    unit: "usd",
    frequency: "daily",
    sourcePath: "/data/macro/stablecoins.json",
    accessor: { kind: "seriesArray", valueKey: "val" },
    description: "스테이블코인 공급량",
    defaultTransform: "rebase100",
    colorToken: "up",
  },
  {
    id: "M2SL",
    label: "M2 Money Stock",
    shortLabel: "M2",
    group: "liquidity",
    unit: "usd_billion",
    frequency: "monthly",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "M2SL" },
    description: "미국 M2 통화량",
    defaultTransform: "yoy",
    colorToken: "brand",
  },
  {
    id: "WALCL",
    label: "Fed Balance Sheet",
    shortLabel: "Fed Assets",
    group: "liquidity",
    unit: "usd_billion",
    frequency: "weekly",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "WALCL" },
    description: "연준 총자산",
    defaultTransform: "rebase100",
    colorToken: "brandAlt",
  },
  {
    id: "WRESBAL",
    label: "Reserve Balances",
    shortLabel: "Reserves",
    group: "liquidity",
    unit: "usd_billion",
    frequency: "weekly",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "WRESBAL" },
    description: "은행 지급준비금",
    defaultTransform: "rebase100",
    colorToken: "info",
  },
  {
    id: "RRPONTSYD",
    label: "Reverse Repo",
    shortLabel: "RRP",
    group: "liquidity",
    unit: "usd_billion",
    frequency: "daily",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "RRPONTSYD" },
    description: "역레포 잔액",
    defaultTransform: "rebase100",
    colorToken: "neutral",
  },
  {
    id: "SOFR",
    label: "SOFR",
    shortLabel: "SOFR",
    group: "rates",
    unit: "percent",
    frequency: "daily",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "SOFR" },
    description: "미국 단기금리",
    colorToken: "down",
  },
  {
    id: "IORB",
    label: "IORB",
    shortLabel: "IORB",
    group: "rates",
    unit: "percent",
    frequency: "daily",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "IORB" },
    description: "지준금 이자율",
    colorToken: "down",
  },
  {
    id: "GDP",
    label: "US GDP",
    shortLabel: "GDP",
    group: "activity",
    unit: "usd_billion",
    frequency: "quarterly",
    sourcePath: "/data/macro/fred-macro.json",
    accessor: { kind: "seriesObject", seriesKey: "GDP" },
    description: "미국 명목 GDP",
    defaultTransform: "yoy",
    colorToken: "brand",
  },
  {
    id: "DGS10",
    label: "10Y Treasury Yield",
    shortLabel: "10Y",
    group: "rates",
    unit: "percent",
    frequency: "daily",
    sourcePath: "/data/macro/fred-banking-daily.json",
    accessor: { kind: "seriesObject", seriesKey: "DGS10" },
    description: "미국 10년 국채금리",
    colorToken: "down",
  },
  {
    id: "HY_spread",
    label: "High Yield Spread",
    shortLabel: "HY Spread",
    group: "credit",
    unit: "spread",
    frequency: "daily",
    sourcePath: "/data/macro/fred-banking-daily.json",
    accessor: { kind: "seriesObject", seriesKey: "BAMLH0A0HYM2" },
    description: "미국 하이일드 스프레드",
    colorToken: "warn",
  },
  {
    id: "bank_credit",
    label: "Commercial Bank Credit",
    shortLabel: "Bank Credit",
    group: "banking",
    unit: "usd_billion",
    frequency: "weekly",
    sourcePath: "/data/macro/fred-banking-weekly.json",
    accessor: { kind: "seriesObject", seriesKey: "TOTLL" },
    description: "상업은행 신용",
    defaultTransform: "yoy",
    colorToken: "brand",
  },
  {
    id: "deposits",
    label: "Bank Deposits",
    shortLabel: "Deposits",
    group: "banking",
    unit: "usd_billion",
    frequency: "weekly",
    sourcePath: "/data/macro/fred-banking-weekly.json",
    accessor: { kind: "seriesObject", seriesKey: "DPSACBW027SBOG" },
    description: "상업은행 예금",
    defaultTransform: "yoy",
    colorToken: "brandAlt",
  },
  {
    id: "fdic_tier1",
    label: "FDIC Tier 1 Ratio",
    shortLabel: "Tier 1",
    group: "banking",
    unit: "percent",
    frequency: "quarterly",
    sourcePath: "/data/macro/fdic-tier1.json",
    accessor: { kind: "dataArray", valueKey: "value" },
    description: "은행 Tier 1 자본비율",
    colorToken: "up",
  },
  {
    id: "oecd_cli_us",
    label: "OECD CLI US",
    shortLabel: "CLI US",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "oecd_cli", valueKey: "united_states" },
    description: "OECD 미국 경기선행지수",
    colorToken: "brand",
  },
  {
    id: "oecd_cli_g7",
    label: "OECD CLI G7",
    shortLabel: "CLI G7",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "oecd_cli", valueKey: "g7" },
    description: "OECD G7 경기선행지수",
    colorToken: "brandAlt",
  },
  {
    id: "pmi_mfg_global",
    label: "Global Manufacturing PMI",
    shortLabel: "Global Mfg",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "pmi_manufacturing", valueKey: "global" },
    description: "글로벌 제조업 PMI",
    colorToken: "neutral",
  },
  {
    id: "pmi_mfg_us_sp",
    label: "US S&P Manufacturing PMI",
    shortLabel: "US Mfg PMI",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "pmi_manufacturing", valueKey: "us_sp_global" },
    description: "미국 S&P Global 제조업 PMI",
    colorToken: "info",
  },
  {
    id: "ism_mfg_headline",
    label: "ISM Manufacturing",
    shortLabel: "ISM Mfg",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "ism_manufacturing", valueKey: "headline" },
    description: "ISM 제조업 헤드라인",
    colorToken: "warn",
  },
  {
    id: "pmi_services_global",
    label: "Global Services PMI",
    shortLabel: "Global Services",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "pmi_services", valueKey: "global" },
    description: "글로벌 서비스업 PMI",
    colorToken: "neutral",
  },
  {
    id: "ism_services_headline",
    label: "ISM Services",
    shortLabel: "ISM Services",
    group: "activity",
    unit: "index",
    frequency: "monthly",
    sourcePath: "/data/macro/activity-surveys.json",
    accessor: { kind: "activity", dataset: "ism_services", valueKey: "headline" },
    description: "ISM 서비스업 헤드라인",
    colorToken: "warn",
  },
] as const;

export const MACRO_CHART_PRESETS: readonly MacroChartPreset[] = [
  {
    id: "risk-liquidity",
    label: "리스크와 유동성",
    description: "주식, 금리, 신용, 통화량을 한 화면에서 본다.",
    series: [
      { id: "sp500", transform: "rebase100" },
      { id: "DGS10", transform: "raw" },
      { id: "HY_spread", transform: "raw" },
      { id: "M2SL", transform: "yoy" },
    ],
  },
  {
    id: "liquidity",
    label: "유동성",
    description: "연준, 재무부, 스테이블코인 유동성 축을 비교한다.",
    series: [
      { id: "WALCL", transform: "rebase100" },
      { id: "WRESBAL", transform: "rebase100" },
      { id: "RRPONTSYD", transform: "rebase100" },
      { id: "tga", transform: "rebase100" },
      { id: "stablecoins", transform: "rebase100" },
    ],
  },
  {
    id: "activity",
    label: "경기활동",
    description: "PMI, ISM, OECD 선행지수를 함께 본다.",
    series: [
      { id: "oecd_cli_us", transform: "raw" },
      { id: "pmi_mfg_us_sp", transform: "raw" },
      { id: "ism_mfg_headline", transform: "raw" },
      { id: "ism_services_headline", transform: "raw" },
    ],
  },
] as const;

export const MACRO_GROUP_LABELS: Record<MacroSeriesDefinition["group"], string> = {
  equity: "주식",
  sentiment: "심리",
  liquidity: "유동성",
  rates: "금리",
  credit: "신용",
  banking: "은행",
  activity: "경기",
};

export const MACRO_TRANSFORM_LABELS = {
  raw: "원값",
  rebase100: "100 기준",
  yoy: "YoY",
  change: "전기 대비",
} as const;

export function seriesById(id: string): MacroSeriesDefinition | undefined {
  return MACRO_SERIES_CATALOG.find((item) => item.id === id) ?? stooqSeriesDefinitionFromId(id);
}
